### ISSUE TITLE
Login Redirect

### ISSUE THREAD

**Issue by filipepferraz** [vimalKeshu/movie-app#2]
Hi, I'm trying to run multi tenancy with two keycloak instances too, but having problems with login path. How you handled the login path for each realm? By default is /sso/login.

**Comment by vimalKeshu** [comment]
You can run the multi tenancy with single keycloak instance by creating separate realms for each one. From front end side, before sending user to login page of keycloak, create another page for selecting tenant(realm).

**Comment by filipepferraz** [comment]
But the login path is hardcoded to /sso/login. How to pass the realm? Here is overriding with the last configured.

**Comment by vimalKeshu** [comment]
I got you. You can avoid it by overriding the configure method in SecurityConfig class which extends the KeycloakWebSecurityConfigurerAdapter.  If you don't define below part then your keycloak adapter will take you on /sso/login page or looking for it in your project.

`      http	
      		.csrf()
      		.disable()
      		.authorizeRequests() 
            .antMatchers("/movie/**").authenticated();`

**Comment by filipepferraz** [comment]
Thanks for the help. I got working making one copy of KeycloakWebSecurityConfigurerAdapter for realm and changing the methods annotated with @Bean (keycloakAuthenticationProcessingFilter(), keycloakPreAuthActionsFilter(), keycloakAuthenticatedActionsFilter() and keycloakSecurityContextRequestFilter()) inserting the realm suffix (to not be replaced after the first @Bean found with same method name). In configuration I extend this copied and changed classes and make a normal configuration. I also overridden the logout url in configure() and override the KeycloakAuthenticationProcessingFilter to replace the default login url. Following that is now working the paths <realm>/login and <realm>/logout.
